GET http://localhost:3000/admin

###
GET http://localhost:3000/database-admin

###
GET http://localhost:3000/
Content-Type: application/json
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbGkiLCJsb2dUaW1lIjoiMTAvMTIvMjAyMSwgNDoyMTo0MSBQTSIsImlhdCI6MTYzNDA1NTcwMn0.PCPpxmKhcu_iywExBDxqKtV2efmBaQvaUTJtoQYo3Zg

###
POST http://localhost:3000/signin
Content-Type: application/json

{
    "username":"dali",
    "password":"thisiszexus"
}

###
POST http://localhost:3000/signup
Content-Type: application/json

{
    "username":"dali",
    "password":"thisiszexus"
}