GET http://localhost:3000/admin

###
GET http://localhost:3000/database-admin

###
GET http://localhost:3000/
Content-Type: application/json
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InpleHVzIiwibG9nVGltZSI6IjEwLzcvMjAyMSwgMTA6MDc6NTcgUE0iLCJpYXQiOjE2MzM2NDQ0Nzd9.K4FbAfx-MqAXtoyhi8zVI8_nrQnKNw0Vzf-dGte2Rf0

###
POST http://localhost:3000/signin
Content-Type: application/json

{
    "username":"zexus",
    "password":"thisiszexus"
}

###
POST http://localhost:3000/signup
Content-Type: application/json

{
    "username":"zexus",
    "password":"thisiszexus"
}